#
# Rules specified here take precedence over default Rubocop config
# Check the guide : https://github.com/rubocop-hq/ruby-style-guide
#

require:
  - rubocop-rails
  - rubocop-performance
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 2.7
  Exclude:
    - Guardfile
    - node_modules/**/*
    - bin/**/*
    - db/**/*
  NewCops: enable


Layout/LineLength:
  Enabled: true
  AutoCorrect: true
  Max: 160

Layout/BlockAlignment:
  Enabled: true
  EnforcedStyleAlignWith: start_of_block

Layout/CaseIndentation:
  Enabled: true
  EnforcedStyle: end

Layout/ClassStructure:
  Enabled: true
  Categories:
    module_inclusion:
      - include
      - prepend
      - extend
    attribute_macros:
      - store_accessor
      - attr_accessor
      - attr_reader
      - attr_writer
    association:
      - belongs_to
      - has_one
      - has_and_belongs_to_many
      - has_many
    macros:
      - validates
      - validate
  ExpectedOrder:
      - module_inclusion
      - constants
      - public_attribute_macros
      - association
      - public_delegate
      - macros
      - public_class_methods
      - initializer
      - public_methods
      - protected_attribute_macros
      - protected_methods
      - private_attribute_macros
      - private_delegate
      - private_methods

Naming/BlockParameterName:
  Enabled: true
  MinNameLength: 3
  AllowedNames:
    - id
    - io
  ForbiddenNames: []

Style/Documentation:
  Enabled: false

Style/SymbolArray:
  Description: 'Use arrays of symbols.'
  EnforcedStyle: brackets
  Enabled: true

Style/WordArray:
  Description: 'Use arrays of words.'
  StyleGuide: '#percent-w'
  Enabled: true
  EnforcedStyle: brackets

Metrics/BlockLength:
  Exclude:
    - 'config/environments/*'
    - 'spec/**/*'

Rails:
  Description: 'Rails specific cops are always run'
  Enabled: true

RSpec/MessageExpectation:
  Enabled: true
  EnforcedStyle: allow

RSpec/MultipleExpectations:
  Enabled: true
  Exclude:
    - 'spec/system/**/*'

RSpec/ExampleLength:
  Enabled: true
  Max: 8
  Exclude:
    - 'spec/system/**/*'

RSpec/EmptyLineAfterExample:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Max: 10
