default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: hastati_development

test:
  <<: *default
  database: hastati_test
  username: <%= ENV['POSTGRES_USERNAME'] || 'kwuteg' %>
  password: <%= ENV['POSTGRES_PASSWORD'] || '' %>

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
