default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: hastati_development

test:
  <<: *default
  database: hastati_test
  <% if ENV['POSTGRES_USERNAME'] %>
  username: ENV['POSTGRES_USERNAME']
  <% end %>
  <% if ENV['POSTGRES_PASSWORD'] %>
  username: ENV['POSTGRES_PASSWORD']
  <% end %>
  # host: localhost
  # port: 5432

production:
  <<: *default
  database: hastati_production
  username: hastati
  password: <%= ENV['HASTATI_DATABASE_PASSWORD'] %>
