default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: hastati_development

<%= if ENV['GIHUB_ACTION_CI'] %>
test:
  <<: *default
  database: hastati_test
  username: postgres
  password: postgres
  host: localhost
  port: 5432
<% else %>
test:
  <<: *default
  database: hastati_test
<% end %>

production:
  <<: *default
  database: hastati_production
  username: hastati
  password: <%= ENV['HASTATI_DATABASE_PASSWORD'] %>
