default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: hastati_development

test:
  <<: *default
  database: hastati_test

production:
  <<: *default
  database: hastati_production
  username: hastati
  password: <%= ENV['HASTATI_DATABASE_PASSWORD'] %>
