default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: hastati_development

# test:
#   <<: *default
#   database: hastati_test

test:
  database: <%= ENV["POSTGRES_DB"] %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD") %>
  username: <%= ENV['POSTGRES_USER'] %>

production:
  <<: *default
  database: hastati_production
  username: hastati
  password: <%= ENV['HASTATI_DATABASE_PASSWORD'] %>
